# Generated by Django 5.1.4 on 2025-08-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short name or title for the property', max_length=200)),
                ('property_type', models.CharField(choices=[('room', 'Room'), ('flat', 'Flat'), ('paying_guest', 'Paying Guest'), ('house', 'House'), ('office', 'Office'), ('hostel', 'Hostel'), ('shop', 'Shop'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('district', models.CharField(choices=[('Gangtok', 'Gangtok'), ('Mangan', 'Mangan'), ('Namchi', 'Namchi'), ('Gyalshing', 'Gyalshing'), ('Pakyong', 'Pakyong'), ('Soreng', 'Soreng')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('kitchen', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'property',
            },
        ),
    ]
