# Generated by Django 5.1.4 on 2025-08-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='city',
            new_name='area',
        ),
    ]
