# Generated by Django 5.1.4 on 2025-08-21 13:44

import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gender_preference',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=property.models.property_image_upload_path),
        ),
    ]
