# Generated by Django 5.1.4 on 2025-08-24 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='uploaded_by',
            field=models.ForeignKey(default=1, help_text='User who uploaded this property', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_properties', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
