# Generated by Django 5.1.4 on 2025-08-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sociallink',
            table='public_social_link',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='public_team_member',
        ),
    ]
