# Generated by Django 5.1.4 on 2025-08-21 15:57

import public.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_sociallink_table_alter_teammember_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='image_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=public.models.team_member_image_upload_path),
        ),
    ]
